version: "3.8"

services:
  # postgres_db:
  #   container_name: postgres_db
  #   image: postgres:alpine
  #   env_file: default.env
  #   hostname: db
  #   restart: always
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   expose:
  #     - 5432

  mongo_db:
    container_name: mongo_db
    restart: unless-stopped
    image: mongo:latest
    env_file: default.env
    hostname: db
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017


  redis_cache:
    restart: unless-stopped
    container_name: redis_cache
    image: 'redislabs/redismod'
    hostname: cache
    ports:
      - 6379:6379

  redis_sessions:
    restart: unless-stopped
    container_name: redis_sessions
    image: 'redislabs/redismod'
    hostname: sessions
    ports:
      - 6378:6379

  backend:
    container_name: modpackmaker_backend
    restart: unless-stopped
    build: ./modpackmaker_backend
    hostname: backend
    ports:
      - 3000
    env_file:
      - default.env
    depends_on:
      - redis_cache
      - mongo_db

  curseforge_api:
    container_name: modpackmaker_curseforge_api
    restart: unless-stopped
    build: ./curseforge_api_proxy
    hostname: curseforge
    ports:
      - 3000
    env_file:
      - default.env
    depends_on:
      - redis_cache


  modrinth_api:
    container_name: modpackmaker_modrinth_api
    restart: unless-stopped
    build: ./modrinth_api_proxy
    hostname: modrinth
    ports:
      - 3000
    env_file:
      - default.env
    depends_on:
      - redis_cache


  nginx:
    container_name: nginx_server
    restart: unless-stopped
    build: ./modpackmaker_react_client
    ports:
      - 80:80
      # - 81:81
      - 443:443
    depends_on:
      - curseforge_api
      - modrinth_api
      - backend
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  # nginx-dashboard:
  #   image: 'docker.io/jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
volumes:
  db_data:
  data:
  letsencrypt:


  
